<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MacBooks-MacBook-Pro.local" failures="0" tests="1" name="runner.Runner" time="16.842" errors="1" timestamp="2022-01-22T17:24:27 GMT" skipped="0">
  <testcase classname="runner.Runner" name="runScenario" time="16.842">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at stepdefinitions.Login.verify_user_is_able_to_successfully_login(Login.java:57)
at âœ½.Verify user is able to successfully login(file:///Users/macbookpro/Documents/Selenium/FrameworkProj1/src/test/java/features/Login.feature:8)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runner.Runner -->
